# Generated by Django 4.1.3 on 2022-12-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='mini_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
